### ISSUE TITLE
CocoaSecurityEncoder

### ISSUE THREAD

**Issue by jasperblues** [kelp404/CocoaSecurity#1]
. . . crashes when attempting to encode an empty string.

**Comment by kelp404** [comment]
Hi, @jasperblues ,

Thank you for commenting this issue.
Could you paste your code?

This is CocoaSecurityEncoder's interface:

``` objective-c
@interface CocoaSecurityEncoder : NSObject
- (NSString *)base64:(NSData *)data;
- (NSString *)hex:(NSData *)data useLower:(BOOL)isOutputLower;
@end
```

You should call messates with `NSData` not `NSString`.
Like these:

``` objective-c
CocoaSecurityEncoder *encoder = [CocoaSecurityEncoder new];

[encoder hex:[NSData new] useLower:YES]
[encoder hex:[@"" dataUsingEncoding:NSUTF8StringEncoding] useLower:YES]
```

**Comment by jasperblues** [comment]
Hi - great lib! 

My code is as follows: 
- (NSString_)encodeUTF8String:(NSString_)string
  {
  return [self encodeStringString:string encoding:NSUTF8StringEncoding];
  }
- (NSString_)encodeStringString:(NSString_)string encoding:(NSStringEncoding)encoding
  {
  NSString\* encoded = @"";
  if ([string length] > 0)
  {
      CocoaSecurityEncoder\* encoder = [CocoaSecurityEncoder new];
      encoded = [encoder base64:[string dataUsingEncoding:encoding]];
  }
  return encoded;
  }

I believe it should not be necessary to test for an empty or nil string as above, however currently I'm getting a crash on empty string. . . (String is not null, but has length of zero. . . I haven't tested for nil string).

**Comment by kelp404** [comment]
Hi, @jasperblues ,

There are some issues in Base64 encoder.
I will fix that.

**Comment by jasperblues** [comment]
Great - meantime I have a work-around.
