### ISSUE TITLE
CocoaSecurityResult utf8String return nil

### ISSUE THREAD

**Issue by ghost** [kelp404/CocoaSecurity#15]
NSString *string = @"hello world";
NSString *newString = [[CocoaSecurity aesEncrypt:string key:@"62c6822914cecf7mmebe5e7488217e0c" utf8String];

out:
newString = nil.

**Comment by VivienCormier** [comment]
I have the same problem.

**Comment by zengyuanchen** [comment]
use hex

**Comment by kelp404** [comment]
The result of the encrypting is binary data, so you can't covert it to string with utf-8 encode.
