### ISSUE TITLE
Support CBC for AES256 encoding

### ISSUE THREAD

**Issue by jasperblues** [kelp404/CocoaSecurity#3]
Was just working on a project where the Android version obtained a cipher as follows:

cipher = Cipher.getInstance("AES/CBC/NoPadding");

Have spent hours getting an AES key that matches on iOS. . Finally my method is: 
- (NSString_)AES256encodeWith:(NSString_)key
  {
  char keyPtr[kCCKeySizeAES256 + 1];
  bzero(keyPtr, sizeof(keyPtr));
  
  char ivz[] = {0x6e, 0x79, 0x73, 0x61, 0x64, 0x72, 0x34, 0x38, 0x32, 0x32, 0x36, 0x37, 0x38, 0x39, 0x31, 0x38};
  
  [key getCString:keyPtr maxLength:sizeof(keyPtr) encoding:NSUTF8StringEncoding];
  
  int dataLength = [self length];
  int diff = kCCKeySizeAES256 - (dataLength % kCCKeySizeAES256);
  int newSize = 0;
  
  if (diff > 0)
  {
      newSize = dataLength + diff;
  }
  
  char dataPtr[newSize];
  memcpy(dataPtr, [self bytes], [self length]);
  for (int i = 0; i < diff; i++)
  {
      dataPtr[i + dataLength] = 0x20;
  }
  
  size_t bufferSize = newSize + kCCBlockSizeAES128;
  void\* buffer = malloc(bufferSize);
  
  size_t numBytesEncrypted = 0;
  
  DDLogInfo(@"Size: %d", numBytesEncrypted);
  
  CCCryptorStatus cryptStatus = CCCrypt(kCCEncrypt, kCCAlgorithmAES128, 0x0000, //No padding!!!!!!
          keyPtr, kCCKeySizeAES256, ivz, dataPtr, sizeof(dataPtr), buffer, bufferSize, &numBytesEncrypted);
  
  if (cryptStatus == kCCSuccess)
  {
      CocoaSecurityResult\* result = [[CocoaSecurityResult alloc] initWithBytes:buffer length:numBytesEncrypted];
      return [result base64];
  }
  
  return nil;
  }

It would be good to have an option to obtain a CBC cipher for AES, like the Java above.

**Comment by jasperblues** [comment]
Also it would be good if the Readme or Appledocs contained some light-weight tutorial about AES encoding. . . prior to the aboe issue, I knew nothing about AES style encoding. . . and now I know more than I want to ;)

. . . seriously though, it would be awesome if this library could be my one-stop shop, without having to look elsewhere to implement the requirements.  .  . . just enough info to drive the API, without having to know the internals.

**Comment by kelp404** [comment]
Hello @jasperblues ,

Could you open a pull request?
Thank you.

**Comment by jasperblues** [comment]
I need to do some more research on this. . . I'll come back to you later.
