### ISSUE TITLE
AES not available

### ISSUE THREAD

**Issue by SanderWind** [kelp404/CocoaSecurity#7]
I'm using RubyMotion to create an iPad app.

For securing my data before sending it to my API I want to encrypt it with the `CocoaSecurity.aesEncrypt` method, but I'm getting a 'NoMethodError' when I try to use  this...

The hashing functions are working though.

Do I need to `require` something?!

**Comment by kelp404** [comment]
Hello @SanderWind ,

I think this issue is about Ruby.
Sorry, I do not use Ruby.

**Comment by SanderWind** [comment]
Damn...

When I look for all the methods with `CocoaSecurity.methods` it is listed in there. 
Do you know a work-around maybe? Or should I look for a different AES method for Ruby?

Thanks anyways for the awesome Hash functions :+1:

**Comment by SanderWind** [comment]
OK, I figured out what I did wrong! :smiley: 
I was using the method like this `CocoaSecurity.aesEncrypt(data, key)` instead of using it like this `CocoaSecurity.aesEncrypt(data, key:key)`.

Cost me a day figuring out and a big headache, but problem solved!

Thanks.
